/*
389. Find the Difference
Easy

2065

355

Add to List

Share
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
Accepted
327,810
Submissions
549,755
*/
Solution
/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    a = s.split("").sort()
    b = t.split("").sort()
    for(i=0;i<b.length;i++){
            if(a[i] !== b[i]){
            return b[i]
        }
    }
};

https://leetcode.com/submissions/detail/636280937/